// <auto-generated />
using System;
using Infra.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations.WebcamDb
{
    [DbContext(typeof(WebcamDbContext))]
    [Migration("20240208141445_InitwebcamData")]
    partial class InitwebcamData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Infra.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AuthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AuthDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AuthTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Attendance", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9292),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 2,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9303),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 3,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9304),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 4,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9305),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 5,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9306),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 6,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9309),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 7,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9310),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 8,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9310),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 9,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9311),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 10,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9313),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 11,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9314),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 12,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9314),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 13,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9315),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 14,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9316),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 15,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9317),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 16,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9317),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 17,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9318),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 18,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9320),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 19,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9320),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 20,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9321),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 21,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9322),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 22,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9323),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 23,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9323),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 24,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9324),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 25,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9325),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 26,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9326),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 27,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9326),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 28,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9327),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 29,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9334),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 30,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9335),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 31,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9336),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 32,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9337),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 33,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9337),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 34,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9339),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 35,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9340),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 36,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9341),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 37,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9341),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 38,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9342),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 39,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9343),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 40,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9344),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 41,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9344),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 42,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9345),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 43,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9346),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 44,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9347),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 45,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9347),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 46,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9348),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 47,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9349),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 48,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9349),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 49,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9350),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 50,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9351),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 51,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9352),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 52,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9352),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 53,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9353),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 54,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9354),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 55,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9354),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 56,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9355),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 57,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9356),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 58,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9357),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 59,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9357),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 60,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9358),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 61,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9359),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 62,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9359),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 63,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9360),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 64,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9361),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 65,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9361),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 66,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9363),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 67,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9364),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 68,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9365),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 69,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9365),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 70,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9366),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 71,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9367),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 72,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9367),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 73,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9368),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 74,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9369),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 75,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9370),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 76,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9370),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 77,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9371),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 78,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9372),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 79,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9373),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 80,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9373),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 81,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9374),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 82,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9375),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 83,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9375),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 84,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9376),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 85,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9377),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 86,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9377),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 87,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9378),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 88,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9379),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 89,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9380),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 90,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9380),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 91,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9381),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 92,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9382),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 93,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9382),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 94,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9383),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 95,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9384),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 96,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9385),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 97,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9385),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 98,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9386),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 99,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9387),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 100,
                            AuthDate = new DateTime(2024, 2, 8, 21, 14, 45, 298, DateTimeKind.Local).AddTicks(9387),
                            AuthDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
