// <auto-generated />
using System;
using Infra.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations.WebcamDb
{
    [DbContext(typeof(WebcamDbContext))]
    partial class WebcamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Infra.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AuthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AuthDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AuthTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Attendance", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6401),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6409),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 2,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6412),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6413),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 3,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6414),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6414),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 4,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6415),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6416),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 5,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6417),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6417),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 6,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6420),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6420),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 7,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6421),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6422),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 8,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6423),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6423),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 9,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6424),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6424),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 10,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6426),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6427),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 11,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6427),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6428),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 12,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6429),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6429),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 13,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6430),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6430),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 14,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6431),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6432),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 15,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6432),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6433),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 16,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6434),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6434),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 17,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6435),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6435),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 18,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6437),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6438),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 19,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6438),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6439),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 20,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6440),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6440),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 21,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6441),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6441),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 22,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6442),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6443),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 23,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6443),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6444),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 24,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6445),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6446),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 25,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6446),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6447),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 26,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6448),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6448),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 27,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6449),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6449),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 28,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6450),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6451),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 29,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6451),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6452),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 30,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6453),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6453),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 31,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6454),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6454),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 32,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6455),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6456),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 33,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6457),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6457),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 34,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6459),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6459),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 35,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6460),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6461),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 36,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6461),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6462),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 37,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6463),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6463),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 38,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6464),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6465),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 39,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6465),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6466),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 40,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6467),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6467),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 41,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6468),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6468),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 42,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6469),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6470),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 43,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6470),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6471),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 44,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6472),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6472),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 45,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6473),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6473),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 46,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6474),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6475),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 47,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6476),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6476),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 48,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6477),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6477),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 49,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6478),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6479),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 50,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6479),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6480),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 51,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6481),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6481),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 52,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6482),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6482),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 53,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6483),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6484),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 54,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6485),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6485),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 55,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6486),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6486),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 56,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6494),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6494),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 57,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6495),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6495),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 58,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6496),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6497),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 59,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6498),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6498),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 60,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6499),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6499),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 61,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6500),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6501),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 62,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6501),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6502),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 63,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6503),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6503),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 64,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6504),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6504),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 65,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6505),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6506),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 66,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6507),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6508),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 67,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6509),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6509),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 68,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6510),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6511),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 69,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6511),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6512),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 70,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6513),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6513),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 71,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6514),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6514),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 72,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6515),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6516),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 73,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6516),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6517),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 74,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6518),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6518),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 75,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6519),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6519),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 76,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6520),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6521),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 77,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6521),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6522),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 78,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6523),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6523),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 79,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6524),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6524),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 80,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6525),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6526),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 81,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6527),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6527),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 82,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6528),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6529),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 83,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6529),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6530),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 84,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6531),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6531),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 85,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6532),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6532),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 86,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6533),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6534),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 87,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6534),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6535),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 88,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6536),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6536),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 89,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6537),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6537),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 90,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6538),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6539),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 91,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6539),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6540),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 92,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6541),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6541),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 93,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6542),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6543),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 94,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6543),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6544),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 95,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6545),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6545),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 96,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6546),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6546),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 97,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6547),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6548),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 98,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6548),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6549),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        },
                        new
                        {
                            Id = 99,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6550),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6550),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 0,
                            UserID = 5674
                        },
                        new
                        {
                            Id = 100,
                            AuthDate = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6551),
                            AuthDateTime = new DateTime(2024, 2, 8, 22, 14, 15, 465, DateTimeKind.Local).AddTicks(6551),
                            AuthTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "Webcam EZVIZ",
                            Flag = 1,
                            UserID = 5677
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
